name: Rubocop

on: [pull_request]

jobs:
  lint:
    name: rubocop
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
      - name: rubocop
        run: bundle exec rubocop --parallel
