name: Rubocop Linter

on:
  push:
    branches-ignore:
      - 'master'

jobs:
  lint:
    runs-on: ubuntu-18.04

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Rubocop linter
        uses: andrewmcodes-archive/rubocop-linter-actions
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

